### ISSUE TITLE
[ERROR] OSError: [Errno 30] Read-only file system: 'Ogre-raw-data-report.txt'

### ISSUE THREAD

**Issue by vfedotovs** [vfedotovs/aws_labmda_sslv_scrape_job#3]
2023-02-19T00:15:30.198+00:00	START RequestId: 29a93056-839d-46f5-8dd4-ef3c4f341529 Version: $LATEST

2023-02-19T00:15:35.616+00:00	Extracting data from message URL 1

2023-02-19T00:15:35.616+00:00

Copy
[ERROR] OSError: [Errno 30] Read-only file system: 'Ogre-raw-data-report.txt'
Traceback (most recent call last):
  File "/var/task/app.py", line 138, in handler
    extract_data_from_url(valid_msg_urls)
  File "/var/task/app.py", line 40, in extract_data_from_url
    write_line(current_msg_url, dest_file)
  File "/var/task/app.py", line 63, in write_line
    with open(file_name, 'a') as the_file:
[ERROR] OSError: [Errno 30] Read-only file system: 'Ogre-raw-data-report.txt' Traceback (most recent call last):   File "/var/task/app.py", line 138, in handler     extract_data_from_url(valid_msg_urls)   File "/var/task/app.py", line 40, in extract_data_from_url     write_line(current_msg_url, dest_file)   File "/var/task/app.py", line 63, in write_line     with open(file_name, 'a') as the_file:

**Comment by vfedotovs** [comment]
Resolved  in #4
